### PR TITLE
Update and fix test suite

### PR DESCRIPTION
**Pull request by clhunsen**
### Prerequisites

- [X] I adhere to the coding conventions (described [here](https://github.com/se-passau/coronet/blob/master/CONTRIBUTING.md)) in my code.
- [x] I have updated the copyright headers of the files I have modified.
- [X] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [X] I have put signed-off tags in *all* commits.
- [X] I have updated the changelog file [NEWS.md](https://github.com/se-passau/coronet/blob/master/NEWS.md) appropriately.
- [X] The pull request is opened against the branch `dev`.

### Description

This PR is mainly concerned with the test suite and compatibility with Travis CI:
- fix tests failing for R 3.3,
- add R 3.6 to test suite, and
- improve `.travis.yml` to fix warnings.
 
#### Changed/Improved

- Add R version 3.6 to test suite (8b2a52d38475a59c55feb17bb54ed12b9252a937, #161)
- Update `.travis.yml` to improve compatibility with Travis CI (41ce589b3b50fd581a10e6af33ac6b1bbea63bb8)

#### Fixed

- Ensure sorting of commit-count and LOC-count data.frames to fix tests with R 3.3 (33d63fd50c4b29d45a9ca586c383650f7d29efd5)

### CODE REVIEW

**Comment by bockthom** [comment]
Nice work @clhunsen. Thanks a lot!

I am a little bit surprised that we did not add the commit regarding R version 3.6 earlier - the commit is half a your old. But better late than never ;)

Regarding the failing tests on R 3.3: Why didn't we recognize this earlier? The tests seem to have failed on the code of the last pull request. That's weird and should not happen again. @clhunsen Do you have any suggestions on how to recognize this earlier? How did you recognize that? May be helpful to get some advice from you for future development.

This pull request looks good. So I will merge it this week,  right after you will have replied to my questions ;)

**Comment by clhunsen** [comment]
> I am a little bit surprised that we did not add the commit regarding R version 3.6 earlier - the commit is half a y[ea]r old. But better late than never ;)

I just forgot about that commit and just "re-found" while rebasing my development branch last week. :wink::sweat_smile: 

> Regarding the failing tests on R 3.3: Why didn't we recognize this earlier? The tests seem to have failed on the code of the last pull request. That's weird and should not happen again. @clhunsen Do you have any suggestions on how to recognize this earlier? How did you recognize that? May be helpful to get some advice from you for future development.

This is (potentially) caused by an update of an R package that is a dependency of the package `sqldf`. With that package update, the tests started to fail: not only for the upstream development branch but also my dev branch on my fork (although, mysteriously only causing issues with R 3.3).

I realized the failures because the cron jobs of Travis CI failed (see [here](https://travis-ci.com/se-passau/coronet/builds) and [here](https://travis-ci.com/clhunsen/coronet/builds), look for the label `cron`). After that @hechtlC and I debugged and discussed a little, coming up with the changes of this PR then.
Maybe, @ChristianKaltenecker can grant you access to the Travis app for this repository. (I am not sure anymore how this exactly works...)

> This pull request looks good. So I will merge it this week, right after you will have replied to my questions ;)

Then, this PR is fine for merging now. :grin:

**Comment by bockthom** [comment]
> I realized the failures because the cron jobs of Travis CI failed (see [here](https://travis-ci.com/se-passau/coronet/builds) and [here](https://travis-ci.com/clhunsen/coronet/builds), look for the label `cron`). After that @hechtlC and I debugged and discussed a little, coming up with the changes of this PR then.
> Maybe, @ChristianKaltenecker can grant you access to the Travis app for this repository. (I am not sure anymore how this exactly works...)

I already have access to the Travis CI jobs. As I also can reach the settings page an travis, I think that I already have full access on that (at least, it looks like that, don't know if there is more than what I can see).

Regarding how you realized the failures: Did you access the travis page for cron jobs on purpose or by chance? Or do you get regular notifications for them?
I can see all the cron job runs on travis, but I never had a look at them before. So, it may be a good idea to regularly check for failing jobs ;)

**Comment by clhunsen** [comment]
> Regarding how you realized the failures: Did you access the travis page for cron jobs on purpose or by chance? Or do you get regular notifications for them?

I enabled email notifications [here](https://travis-ci.com/account/preferences). Thus, I get emails when jobs are failing. The failing jobs bugged me for quite some time already, I just had no time to fix the underlying issue until now.

> I can see all the cron job runs on travis, but I never had a look at them before. So, it may be a good idea to regularly check for failing jobs ;)

That may be a good idea. :grinning::+1: You can also add https://travis-ci.com/dashboard to your bookmarks and regularly check for obscurities. :wink: (The link is especially useful if you have several repositories on Travis.)

**Pull request merged**
